### ISSUE TITLE
TODO nu version

### ISSUE THREAD

**Issue by ykonoclast** [ykonoclast/UPolaris#25]
- [x] p.17 dégats échelle V-/échelle H mal dit et table modif degat dit RD et -1 par niveau
- [x] ERRATA : noyade telle que pratiquee dans partie intro
- [x] p.25 pas un jet par tour de combat (durée en fait indiquée dans les descriptions)
- [x] calcul sol tir : pas malus 15 mais jet respectivement moyen et difficile
- [x] mettre niv par defaut appareils (LdB2 dit 15 pour les sonscans et autres, voir s'il y a des niveaux indiqués pour les armures et si, pour les vaisseaux, les postes de détection donnent des valeurs ; sinon aviser des modificateurs de NT par exemple avec le 15 en baseline).
- [x] Indiquer aux divers endroits idoines de se référer à l'annexe bibliographique pour les listes de matos (torpilles etc.).
- [x] phase approche torp : verifier
- [x] notes matos : torpille comment? [signifie sans doute comment les acquérir, la liste..]
- [x] Séparer règles des engins du combat en engin
- [x] MAtos : récap de la puissance explosive p.60-62
- [x] Solution tir un degré de plus si entree au pif sans analyse mais avec du visu?
- [x] NOTES AU DEBUT DU DOC (notamment blindage électronique et autres éléments en fait cruciaux comme régulateurs thermiques et passage à l'échelle) ; ajouter toute une section sur ce qui est valide/invalide dans LdB2 et GT (tropilles je prends où, matos indispensable pareil : en lien avec la discussion dans le doc des régulateurs thermiques dans un bouquin et pqas l'autre)
- [x] Revoir tous les calculs : le jet moyen de trait est de 10, celui de comp 15. Changer modificateurs et dire jet moyyen pour matos et difficile pour opérateur au lieu de malus de 15.
- [x] réparations si pas déjà traité (cf p.10 ldb2), récupérer pièce détachée (test chance quand cassé ou canibalisé) : jet de 1D10 <= points restants du rang actuel : si réussi on peut réparer sans pièces détachées, sinon il en faudra (prix égal [5-rang de fiabilité]×10% du coût de base de l'équipement). MJ estime chances que ce soit sur bout de matos déjà existant.
- [x] réparations  : comment restaurer l'ITG des éléments d'un engin : dire que jet dientique à pour matos habituel mais temps et coût identique à avarie légère PAR JET EFFECTUE.
- [x] réparation : ldb2 p.10 un incr ou bonus 5 par NT d'écart réparateur/équipement (notamment matos du gars)
- [x] Rajouter des renvois aux diverses sections, notamment pour les pertes d'ITG et dégats
- [x] PRix des armures et vaisseaux : diviser par 50 et appliquer ensuite les règles d'UPolaris, faire 2d6+8 ITG à chaque système et possibilité d'aqcquérir à ITG spécifique (en ce cas ITG lobale)
- [x] IEM à mettre dans partie MATOS (et vérif fonctionnement) :IEM : une attaque IEM impose un test de panne au matériel électronique touché avec un malus égal au niveau de l’attaque dans Polaris (donc doublé en UP!System). Un blindage IEM réduit le niveau de l’attaque.
Le coût du blindage IEM est égal à 5 % du prix de base du matériel × niveau × niveau.
- [x] Pas confondre blindage électronique (qui contre les brouillages, atténuateurs de bruits etc.) et blindage IEM qui contre les IEM spécifiquement.
- [x] attaque IEM des armures et véhicules (il y a des règles spécifiques)
- [x] Assitance au tir électronique?
- [x] Sas?
- [x] PoidsMun MP MD Alliance Polaire 107-108 (et checker aussi autres suppléments de "back" pour ce type de petite règle sympa)
- [x] recheccher profondeur et pression dans GT et LDB en faitt (p103 prof torpilles par ex)
- [x] Rang fiabilité max = rang actuel +1 avec max 5 et on peut avoir jusqu'au dernier point d'ITG du rang actuel bien ûr (exemple : 4 rangs et 4 points pour un nombre total de 24 points d'ITG, mais pas exactement 25 et le rang 5).
- [x] ordinateurs [!!!! reporter la règle de renvoi aux cyberdeck dans la section matos] à simplifier et mutualiser avec règles cyber up ; fonctionalité utilitaire (?) pour armes réatives, détection etc s'inspire de la page 22 de ldb2)
- [x] matos deux modes (assit ET bonus) +15 à la diff si manu (mais parfois arbitrer), particu analys et sonar
- [x] détails notamment pén (pas champs etc.) p.36 LdB2
- [x] Rappeler règle des champs (à partir p.66)
- [x] p208, chalps/armure endommagées
- [x] rappeler règle cumul et malus armure et classes/types d'armure (le tout p.63)
- [x] Tropilles!!!!
- [x] comment régler panne : pas juste restaurer ITG ; introduire distinction dépanner réparer [matos général]
- [x] Règles respiration de fluide (avec athlétisme?) 
- [x] action au lieu d'arts physiques dans les tableaux hybrides et texte
- [x] Fluide, l'opération pour descendre en dessous-de (vérifier) coûtera 4XP
- [x] patrouiller les tableaux non utilisés du calc, why?
- [x] Règles drogues poisons et maladaies
- [x] Toxicité des munitions p306
- [x] profondeur dét/comm p284 GT mais aussi autres (voir UPolaris qui a peut etre une meilleure liste)
- [x] Lister mélanges et fluides pour ne plus se référer au LdB1
- [x] influenced e la pression en divers lieux (notamment ldb2 p14 et voir upolaris pour autres rencvois)
- [x] temps de compression
- [x] decompression entre autre GT 275-278
- [x] Préciser qu'on n'utilisera plus le LdB1 dans l'intro (dire qu'on n'utilise de Polaris que les listes de matos, maladies etc. et aucune règle donc parties du LdB2 et rien du LdB1) et "patrouiller" le LdB1 pour vérifier que rien d'intéressant n'y traîne
- [x] mutations dont mutations solaires de l'altération (univers)
- [x] reprendre touts les machins de la surface (phénomènes) car UPOlaris ne fait qu'ü renvoyer
- [x] Polarsi dont POlaris solaire en reprenant octopus347 
- [x] Frogues poisons et maladies à lister d'unviers
- [x] Tolérance et controle COE?
- [x] Acquisition e matos lourd (vaisseaux, armures, vu les prix délirants du GT : essayer de revenir aux équilibres du kit de survie)
- [x] Prix matos avec offre et demande p375 univers ; surtout checker les valeurs de prix avec l'info des 30% du prix affiché en marché noir
- [x] usure et deterioriation materiel, ldb2-208
- [x] autres regles avancees ldb2 à la fin mais voir si la rupture tech de la p.210 n'ést pas mieux gérée par le GT déjà.
- [x] règles cyborg all pol + Discipline et autres de Rep Cor et regarder Union Med
- [x] pression p250 ldb1 voir si autres machins deleteres du meme ordre
- [x] Errata : gabarit
- [x] Errata : p.131 base de manoeuvre est plutot base d'init en fonction de commandes
- [x] Errata : exposition directe à climat extrême 5 choc par tour et 5 phy par tour en plus si grave (en dessous de 0, contact à surface chaude ou flamme nue etc.)
- [x] renvoi à table conversion V-
- [x] Refaire intro pour dire que la connaissancede Polaris est nécessaire même si ce n'ést pas une simple couche de conversion
- [x] Repasser par toutes règles UPOL pour voir amés possibles et si on peut pas juste reprendre Polaris en l'état
- [x] Repasser par Polaris (dont fin du GT!!) aussi pour reprendre des trucs par-ci par là comme les tourbillons sous marins et autre notamment :  Matériaux : guide technique, table p.298.
Pénétration en fonction de la distance : guide technique, p.297.
- [x] ERRATA : généraliser système passion au-delà de peur
- [x] ERRATA : jet de trait facile est ND5
- [x] Faire tour par les autres issues et en créer une pour transcrire les mutations de l'altération moléculaire (Avec pages idoines).
